# -*- coding: utf-8 -*-
# https://www.youtube.com/watch?v=je9Cj7G5pnY
# Form implementation generated from reading ui file 'JumpGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
# create the GUI in Qt Designer called JumpGui
# open a command prompt
# chdir to d:/Python Code/JumpPyQtGraph
# pyuic5 -x JumpGui.ui -o JumpGui.py

from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget
import numpy as np


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1148, 697)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnPlotJump = QtWidgets.QPushButton(self.centralwidget)
        self.btnPlotJump.setGeometry(QtCore.QRect(54, 200, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnPlotJump.setFont(font)
        self.btnPlotJump.setObjectName("btnPlotJump")
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(220, 40, 891, 571))
        self.graphicsView.setObjectName("graphicsView")
        self.btnClearGraph = QtWidgets.QPushButton(self.centralwidget)
        self.btnClearGraph.setGeometry(QtCore.QRect(50, 250, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnClearGraph.setFont(font)
        self.btnClearGraph.setObjectName("btnClearGraph")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1148, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btnPlotJump.clicked.connect(lambda: self.draw())
        self.btnClearGraph.clicked.connect(lambda: self.clear())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnPlotJump.setText(_translate("MainWindow", "Plot Jump Data"))
        self.btnClearGraph.setText(_translate("MainWindow", "Clear"))

    def draw(self):
        data_load = np.loadtxt("D:/Avunte SUPER Jump/AvunteCMJ.csv", skiprows=2, delimiter=",")
        t = data_load[:, 0]
        fz = data_load[:, 1]
        self.graphicsView.plot(t, fz)

    def clear(self):
        self.graphicsView.clear()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

